# Hands On: Data Import and Manipulation

In [5]:
import numpy as np
import pandas as pd

## Introduction to Python for Machine Learning

### Create an array of 10 random integers between 1 and 100, and then calculate the mean and standard deviation of the array.

In [6]:
np.random.seed(42)

random_array = np.random.randint(1, 101, size=10)

mean = np.mean(random_array)

std_dev = np.std(random_array)

print("Random Array:", random_array)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Random Array: [52 93 15 72 61 21 83 87 75 75]
Mean: 63.4
Standard Deviation: 25.370061095708856


### Create a 2-dimensional array of 3 rows and 4 columns with random integer values. Then, calculate the sum of each row and column.


In [7]:
array_2d = np.random.randint(1, 101, size=(3, 4))

row_sums = np.sum(array_2d, axis=1)

column_sums = np.sum(array_2d, axis=0)

print("2-Dimensional Array:")
print(array_2d)
print("\nSum of each row:", row_sums)
print("Sum of each column:", column_sums)

2-Dimensional Array:
[[ 88 100  24   3]
 [ 22  53   2  88]
 [ 30  38   2  64]]

Sum of each row: [215 165 134]
Sum of each column: [140 191  28 155]


### Create a DataFrame with 3 columns: "Name", "Age", and "City". Add at least 5 rows of data to the DataFrame. Then, filter the DataFrame to only include rows where the person's age is greater than or equal to 30.


In [10]:
dataframe = {
        "Name": ["Alejandro", "Isaac", "Gutenberg", "Ivan", "Donald"],
        "Age": [25, 23, 21,49,79],
        "City": ["Quito", "Quito","Manta","Ambato", "Miami"]
}

In [11]:
df = pd.DataFrame(dataframe)

filtered_df = df[df["Age"] >= 30]

print("Age is greater than: ")
print(filtered_df)

Age is greater than: 
     Name  Age    City
3    Ivan   49  Ambato
4  Donald   79   Miami


###  Load a CSV file into a DataFrame and then calculate the mean, median, and mode of one of the columns in the DataFrame.

In [12]:
df = pd.read_csv('riyadh_cafes.csv')
df.head(5)

index               coffeeName  rating  rating_count   
0      0               Cacti Cafe     4.2          2212  \
1      1          فازا قهوة مختصة     4.3           889   
2      2                    ناريز     3.8            39   
3      3  Fc Lounge - اف سي لاونج     3.5           539   
4      4                    PEAKS     4.6            25   

                                                 url  24_hours         lon   
0  https://www.google.com/maps/place/Cacti+Cafe/d...      True  24.8339855  \
1  https://www.google.com/maps/place/%D9%81%D8%A7...     False  24.7724577   
2  https://www.google.com/maps/place/%D9%86%D8%A7...     False  24.8072766   
3  https://www.google.com/maps/place/Fc+Lounge+-+...      True  24.8131149   
4  https://www.google.com/maps/place/PEAKS/data=!...     False   24.742045   

          lan  
0  24.8339855  
1  24.7724577  
2  24.8072766  
3  24.8131149  
4   24.742045

In [19]:
print('Mean: ',df['rating_count'].mean())
print('\nMedian: ',df["rating_count"].std())
print("\nMode: ",np.array(df['rating_count'].mode()))

Mean:  260.8210042161748

Median:  613.3163601237649

Mode:  [1]


### Create a scatter plot of random x and y values between 1 and 100.